# Linear Algebra

### This notebook will use Python and Numpy to script some basic linear algebra concepts. We will avoid using numpy and scipy linalg functions because they hide the mechanics of the calculations which is counter to the aim of learning and understanding the topic. Strongly recommend doing the calculations by hand as well as using the functions here and comparing the answers.


In [98]:
import numpy as np
import matplotlib.pyplot as plt

## Solving systems of equations

### Part 1: Gaussian elimination

First we will define some functions to allow us to perform some elementary row operations. We will then use these elementary row functions to reorganise the array A into row echelon form, then we can solve it to find values from x, y and z that satisfy all 3 equations.

First, we will need to swap rows.
Second, we need a way to multiply individual rows by a scalar in place.
Finally, we need a way to add multiples of rows to other rows.

In [99]:

def SwapRows(A, idx1, idx2):
    
    temp = A[idx2,:].copy()
    A[idx2,:] =A[idx1,:]
    A[idx1,:] = temp

    return A


def multiply_row(A,idx1,multiple):

    A[idx1,:]=A[idx1,:]*multiple

    return A



def add_rows(A,add_to,add_from,multiple):

    # start with identity matrix
    E1 = np.array([[1,0,0],[0,1,0],[0,0,1]])

    E1[add_to,add_from] = multiple

    A = E1@A

    return A


Now we have these elementary row operations available to us, we can start to rearrange an array into row echelon form.

Let's set up an initial array that represents the following system of 3 linear equations:

$x + 2y + 3z = 24$

$2x - y + z = 3$

$3x + 4y -5z = -6$


In [100]:
A = np.array([[1,2,3,24],[2,-1,1,3],[3,4,-5,-6]])

print(A)

[[ 1  2  3 24]
 [ 2 -1  1  3]
 [ 3  4 -5 -6]]


The following sequence of swaps, additions and multiplications reorganizes the array into row echelon form. hThere is probably a more efficient route - I determined this way to work, please feel free to try to find a better sequence.

In [101]:

A = SwapRows(A,0,1)
A = SwapRows(A,0,2)
A = SwapRows(A,1,2)
A = add_rows(A,1,2,-1)
A = add_rows(A,1,2,-1)
A = SwapRows(A,1,2)
A = add_rows(A,0,2,-1)
A = add_rows(A,0,1,-3)
A = SwapRows(A,0,1)
A = multiply_row(A,1,5)
A = add_rows(A,1,2,3)
A = SwapRows(A,1,2)


print("Array A in Row Echelon Form\n\n",A)

Array A in Row Echelon Form

 [[   1    2    3   24]
 [   0   -5   -5  -45]
 [   0    0  -60 -300]]


This yields a sequence of equations that can easily be solved by cascading variable values up the array, since:

$-60z = -300$

$-5y -5z = -45$

$x + 2y + 3z = 24$



$$
$$
$ z = -300 / -60$,

so $z = 5 $
$$
$$
$ -5 y - (-5 * 5) = -45$, 
$$
$$
so $y = 4 $
$$
$$
$ z + (2 * 4) + (3 * 5) = 24$, 
$$
$$
so $x = 1 $
$$
$$


This has therefore given the solution to the system of equations:

$x = 1$

$y = 4$

$z = 5$


### Part 2: Gauss-Jordan elimination

We could also achieve this using Gauss-Jordan elimination by reducing the row-echelon form to give the values for x,y and z in the augmented matrix. The aim of this is to reduce the system matrix to be equal to the identity matrix. The augmented matrix then represents the solution to the system of equations.

In [102]:
A = multiply_row(A,0,5)
A = multiply_row(A,1,2)
A = add_rows(A,0,1,0)
A = add_rows(A,0,1,1)
A = multiply_row(A,0,1/5)
A = multiply_row(A,1,-1/10)
A = multiply_row(A,2,-1/60)
A = add_rows(A,0,2,-1)
A = add_rows(A,1,2,-1)

In [103]:
print("A in REDUCED ECHELON FORM\n\n")
print(A)
print()

A in REDUCED ECHELON FORM


[[1 0 0 1]
 [0 1 0 4]
 [0 0 1 5]]



The augmented matrix in reduced row echelon form offers a solution in the form of x, y and z values in rows 0, 1 and 2. Again, this method gives:

$x = 1$

$y = 4$

$z = 5$

### Part 3: Numpy's solver

To be completely sure we have the correct answer we can also fall back to Numpy.linalg's solver. To do this we import the relevant package and pass the system matrix and the augmented matrix as separate variables.

In [104]:
# import our original matrix
A = np.array([[1,2,3,24],[2,-1,1,3],[3,4,-5,-6]])

# separate into system matrix (M) and augmented matrix (b)
M = A[:,0:-1]
b = A[:,-1]

print("System Matrix M:\n")
print("\n",A)
print("\nAugmented matrix, b")
print("\n",b)

System Matrix M:


 [[ 1  2  3 24]
 [ 2 -1  1  3]
 [ 3  4 -5 -6]]

Augmented matrix, b

 [24  3 -6]


In [105]:
from numpy.linalg import solve as slv

x,y,z = slv(M,b)

print("x = ",np.round(x,0))
print("y = ",np.round(y,0))
print("z = ",np.round(z,0))

x =  1.0
y =  4.0
z =  5.0


Success - the three methods all provide the same solutions!